apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: movietvproject
  description: Full-stack service
  annotations:
    backstage.io/source-location: url:https://github.com/AyushDaffodil/MovieTVProject/blob/main/catalog-info.yaml
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: user:default/ayush
  lifecycle: production
  providesApis:
    - movietv-api
  dependsOn:
    - api:default/tmdb-api

---
apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: movietv-api
  description: MovieTV service API
spec:
  type: openapi
  lifecycle: production
  owner: ayush
  definition:
    $text: https://github.com/AyushDaffodil/MovieTVProject/blob/main/catalog-info.yaml


---
apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: tmdb-api
  description: "The Movie Database (TMDB) public API"
  annotations:
    backstage.io/managed-by-location: url:https://api.themoviedb.org
spec:
  type: openapi
  lifecycle: production
  owner: ayush
  definition: 
    $text: https://raw.githubusercontent.com/ckatle/oas-tmdb/master/openapi.yml

---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: ayush
spec:
  profile:
    displayName: Jenny Doe
    email: jenny-doe@example.com
    picture: https://example.com/staff/jenny-with-party-hat.jpeg
  memberOf: []

