apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: movietvproject
  description: Full-stack service
  owner: ayush
spec:
  type: service
  owner: ayush
  lifecycle: production
  providesApis:
    - movietv-api
  dependsOn:
    - api:default/tmdb-api

---
apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: movietv-api
  description: MovieTV service API
spec:
  type: openapi
  lifecycle: production
  owner: ayush
  definition:
    $text: https://raw.githubusercontent.com/AyushDaffodil/MovieTVProject/refs/heads/main/Backend/swaggerContent.yaml


---
apiVersion: backstage.io/v1beta1
kind: API
metadata:
  name: tmdb-api
  description: "The Movie Database (TMDB) public API"
  annotations:
    backstage.io/managed-by-location: https://api.themoviedb.org
spec:
  type: openapi
  lifecycle: production
  owner: ayush

